# Generated by Django 5.0.6 on 2024-07-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "pcpc_ingredientid",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("pcpc_ingredientname", models.CharField(max_length=255)),
                ("NOAEL_CIR", models.JSONField()),
                ("LD50_CIR", models.JSONField()),
                ("LD50_PubChem", models.JSONField()),
                ("value_updated", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
